# fly.toml app configuration file generated for stitches-recipes-db-2 on 2024-05-14T22:04:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stitches-recipes-db-2'
primary_region = 'lhr'

[env]
  FLY_RESTORED_FROM = 'vol_4yjwepo7eyjm2z94'
  PRIMARY_REGION = 'lhr'

[[mounts]]
  source = 'pg_data'
  destination = '/data'

[checks]
  [checks.pg]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/pg'

  [checks.role]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/role'

  [checks.vm]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/vm'

[[metrics]]
  port = 9187
  path = '/metrics'
