# Generated by Django 2.1.7 on 2019-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190207_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooked_count',
            field=models.IntegerField(default=0),
        ),
    ]
