# Generated by Django 2.1.5 on 2019-03-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]