# Generated by Django 4.1.3 on 2022-11-30 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_next_week_remove_recipe_this_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisweekitem',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
