# Generated by Django 4.0.5 on 2022-12-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_thisweekitem_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextWeekMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_week', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ThisWeekMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_week', models.BooleanField()),
            ],
        ),
    ]
