# Generated by Django 4.0.5 on 2022-12-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_nextweekmealitem_thisweekmealitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextweekitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_week', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='thisweekitem',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='this_week', to='recipes.recipe'),
        ),
    ]
