# Generated by Django 4.1.3 on 2022-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_nextweekitem_recipe_alter_thisweekitem_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisweekitem',
            name='position',
            field=models.IntegerField(default=100000),
        ),
    ]
