# Generated by Django 4.0.5 on 2022-12-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_thisweekitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextweekitem',
            name='position',
            field=models.IntegerField(default=100000),
        ),
    ]
