# Generated by Django 4.2.4 on 2024-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_nextweekitem_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep',
            field=models.BooleanField(default=False),
        ),
    ]
