# Generated by Django 4.2.4 on 2025-01-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipe_prep'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='related',
            field=models.ManyToManyField(to='recipes.recipe'),
        ),
    ]
