name: Fly Deploy
on:
  push:
    branches: [ "master" ]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@67ddda2a87628f1aff28a54b8a708879ec62c80f
      - run: flyctl deploy --remote-only
      # wait for new app to start, ideally there would be a way to check rather than just sleeping
      - run: sleep 30
      - run: flyctl ssh console --command "/app/manage.py migrate"
      - run: flyctl ssh console --command "/app/manage.py add_recipes"